
services:

  archivospublicos:
    build:
      context: .
      dockerfile: Dockerfile
    image: archivospublicos:0.0.1
    container_name: archivospublicos
    environment:
       NODE_ENV: "production"
       PORT: ${PORT:-2201}
    ports:
      - "127.0.0.1:2201:2201"