version: "3.9"

services:

  archivospublicos:
    build:
      context: .
      dockerfile: Dockerfile
    image: archivospublicos:0.0.1
    container_name: archivospublicos
    volumes:
      - .:/srv/cf.archivospublicos
      - /srv/cf.archivospublicos/node_modules
      - /srv/cf.archivospublicos/frontend/bower_components
    ports:
      - "2201:80"