FROM node:alpine

CMD mkdir /srv/cf.archivospublicos

COPY ["package.json","/srv/cf.archivospublicos/"]

CMD mkdir -p /srv/cf.archivospublicos/frontend/assets/lib

COPY ["frontend/assets/lib/package.json","/srv/cf.archivospublicos/frontend/assets/lib/"]

WORKDIR /srv/cf.archivospublicos

RUN npm install

RUN npm install -C frontend/assets/lib

COPY [".", "/srv/cf.archivospublicos/"]

EXPOSE $PORT

CMD [ "npm", "run", "dev" ]
