version: "3.9"

x-common-variables: &common-variables
  HOST_ARCHIVOSPUBLICOS: "http://192.168.42.5:2201"
  SESSION_SECRET: "trascender-con-sso"
  COOKIE_DOMAINs: ".jotace.cl"

services:

  archivospublicos:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: archivospublicos:0.0.1
    container_name: archivospublicos
    volumes:
      - .:/srv/cf.archivospublicos/
      - /srv/cf.archivospublicos/node_modules
      - /srv/cf.archivospublicos/frontend/bower_components
    environment:
       <<: *common-variables
       HOST: "http://192.168.42.5:2201"
    ports:
      - "2201:80"
      
#networks:
#  default:
#    external:
#      name: jotace