version: "3.9"

services:

  archivospublicos:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: archivospublicos:0.0.1
    container_name: archivospublicos
    volumes:
      - .:/srv/cf.archivospublicos/
      - /srv/cf.archivospublicos/node_modules
      - /srv/cf.archivospublicos/frontend/bower_components
    environment:
       NODE_ENV: "development"
    ports:
      - "2201:80"
      
#networks:
#  default:
#    external:
#      name: jotace