version: "3.10"

services:

  archivospublicos:
    build:
      context: .
      dockerfile: Dockerfile
    image: archivospublicos:0.0.1
    container_name: archivospublicos
    volumes:
      - .:/srv/cf.archivospublicos/
      - /srv/cf.archivospublicos/node_modules
      - /srv/cf.archivospublicos/frontend/assets/lib/bower_components
    environment:
       NODE_ENV: "production"
       PORT: ${PORT:-2201}
    ports:
      - "${PORT:-2201}:2201"