version: "3.9"

services:

  archivospublicos:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: archivospublicos:0.0.1
    container_name: archivospublicos
    volumes:
      - .:/srv/cf.archivospublicos/
      - /srv/cf.archivospublicos/node_modules
      - /srv/cf.archivospublicos/frontend/bower_components
    environment:
       NODE_ENV: "development"
       PORT: ${PORT:-2201}
    ports:
      - "${PORT:-2201}:2201"